import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>{/* Add your head content here */}</head>
        <body>
          <header>
            <Navbar />
            {/* You can add other header content here */}
          </header>
          <main className="flex items-center justify-center h-full">
            {children}
            {/* The content of individual pages will be inserted here */}
          </main>
          <footer>{/* Add footer content here */}</footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
