import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>{/* Add your head content here */}</head>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header>
              <Navbar />
              {/* You can add other header content here */}
            </header>
            <main className="flex items-center justify-center h-full">
              {children}
              {/* The content of individual pages will be inserted here */}
            </main>
            <footer>{/* Add footer content here */}</footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
